server:
  port: 8080
logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123456
  h2:
    console:
      path: /h2  # http://localhost:8080/h2
      enabled: true

