server:
  port: 8080
logging:
  config: classpath:log4j2.xml


spring:
  cache:  #spring提供缓存
    cache-names: "userCache,cache2"
    type: CAFFEINE
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=10s"
